localeRefactoredSumming=0;
for summingIteration=1:totalIterations
    localeRefactoredSumming(summingIteration)=sum(storeSusceptible(:,summingIteration)) + ...
    sum(storeInfected(:,summingIteration)) + ...
    sum(storeRecovered(:,summingIteration)) + ...
    sum(storeVaccinated(:,summingIteration));
end
localeRefactoredSumming = localeRefactoredSumming +storeMaternity;